# Generated by Django 6.0 on 2025-12-27 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('categorie', models.CharField(choices=[('wax', 'Wax'), ('bazin', 'Bazin'), ('djezner', 'Djezner'), ('tissu', 'Tissu'), ('traditionnel', 'Tenue traditionnelle')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
