# Generated by Django 6.0 on 2025-12-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profils/'),
        ),
    ]
