# Generated by Django 6.0 on 2026-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_annonce_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
