# Generated by Django 4.2.27 on 2026-01-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profil_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='bio',
        ),
    ]
